server:
  port: 8081

tenants:
  default: multitenant1
  datasources:
    multitenant1:
      jdbcUrl: jdbc:postgresql://localhost:5432/multitenant1
      driverClassName: org.postgresql.Driver
      username: postgres
      password: postgres
    multitenant2:
      jdbcUrl: jdbc:postgresql://localhost:5432/multitenant2
      driverClassName: org.postgresql.Driver
      username: postgres
      password: postgres
    multitenant3:
      jdbcUrl: jdbc:postgresql://localhost:5432/multitenant3
      driverClassName: org.postgresql.Driver
      username: postgres
      password: postgres

spring:
  jpa:
    hibernate:
      ddl-auto: update